
default: &default
  # adapter: mysql2
  adapter: pg
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  encoding: utf8
  database: db/development
  pool: 5
  username: postgres
  password: 123456
  host: localhost
  port: 5432

test:
  <<: *default
  adapter: postgresql
  encoding: utf8
  database: db/test
  pool: 5
  username: postgres
  password: 123456
  host: localhost
  port: 5432

production:
  <<: *default
  adapter: postgresql
  encoding: utf8
  database: db/production
  pool: 5
  username: postgres
  password: 123456
  host: localhost
  port: 5432
